- name: Run python setup tools to install Keylime
  shell: "/usr/bin/python3 setup.py install"
  args:
    chdir: /root/keylime

- name: Move keylime.conf into default location
  copy:
    src: /root/keylime/keylime.conf
    dest: /etc
    mode: 0644
    remote_src: yes

- name: Change require_ek_cert to false.
  lineinfile:
    path: /etc/keylime.conf
    regexp: '^require_ek_cert'
    line: require_ek_cert = False

- name: Change ca_implementation to openssl.
  lineinfile:
    path: /etc/keylime.conf
    regexp: '^ca_implementation'
    line: ca_implementation = openssl
